version: '3.8'

services:
  tomcat:
    image: tomcat:9.0-jdk8
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./logs/:/usr/local/tomcat/logs/
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true